<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Assign extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assign_model');
        $this->load->model('Courses_model');
        $this->load->model('Users_model');
        $this->load->model('Curriculam_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of assign
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('assign/index?');
        $config['total_rows'] = $this->Assign_model->get_all_assign_count();
        $this->pagination->initialize($config);

        $data['assign'] = $this->Assign_model->get_all_assign($params);     
        $data['_view'] = 'assign/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new assign ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

		//
		$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
		$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
		$this->form_validation->set_rules('trainerid','Trainerid','trim|required|max_length[10]');
		$this->form_validation->set_rules('batch','Batch','trim|required|max_length[10]');
		$this->form_validation->set_rules('day','Day','trim|required|max_length[255]');
		$this->form_validation->set_rules('adate','Adate','trim|required');
		$this->form_validation->set_rules('attendence','Attendence','trim|required|max_length[10]');

		if($this->form_validation->run())     
        {   
            $params = array(
				//
				'course_id' => $this->input->post('course_id'),
				'studentid' => $this->input->post('studentid'),
				'trainerid' => $this->input->post('trainerid'),
				'batch' => $this->input->post('batch'),
				'day' => $this->input->post('day'),
				'adate' => $this->input->post('adate'),
				'attendence' => $this->input->post('attendence'),
            );
			
            $params=$this->security->xss_clean($params);
		
            $assign_id = $this->Assign_model->add_assign($params);
            redirect('assign/index');
        }
        else
        {  
            $data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
            $data['_view'] = 'assign/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a assign
     */
    function edit($id)
    {   
        // check if the assign exists before trying to edit it
        $data['assign'] = $this->Assign_model->get_assign($id);
        
        if(isset($data['assign']['id']))
        {
            $this->load->library('form_validation');

			// 
			$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
$this->form_validation->set_rules('trainerid','Trainerid','trim|required|max_length[10]');
$this->form_validation->set_rules('batch','Batch','trim|required|max_length[10]');
$this->form_validation->set_rules('day','Day','trim|required|max_length[255]');
$this->form_validation->set_rules('adate','Adate','trim|required');
$this->form_validation->set_rules('attendence','Attendence','trim|required|max_length[10]');

		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					'course_id' => $this->input->post('course_id'),
'studentid' => $this->input->post('studentid'),
'trainerid' => $this->input->post('trainerid'),
'batch' => $this->input->post('batch'),
'day' => $this->input->post('day'),
'adate' => $this->input->post('adate'),
'attendence' => $this->input->post('attendence'),

                );
				$params=$this->security->xss_clean($params);
                $this->Assign_model->update_assign($id,$params);            
                redirect('assign/index');
            }
            else
            {
				$data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
                $data['_view'] = 'assign/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The assign you are trying to edit does not exist.');
    } 

    /*
     * Deleting assign
     */
    function remove($id)
    {
        $assign = $this->Assign_model->get_assign($id);

        // check if the assign exists before trying to delete it
        if(isset($assign['id']))
        {
            $this->Assign_model->delete_assign($id);
            redirect('assign/index');
        }
        else
            show_error('The assign you are trying to delete does not exist.');
    }
    
}