<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Attendance extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Attendance_model');
        $this->load->model('Courses_model');
        $this->load->model('Users_model');
        $this->load->model('Curriculam_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of attendance
     */
    function index()
    {
      

        $data['attendance'] = $this->Attendance_model->get_all_attendance();     
        $data['_view'] = 'attendance/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new attendance ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

		//
		$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
		$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
		$this->form_validation->set_rules('trainerid','Trainerid','trim|required|max_length[10]');
		$this->form_validation->set_rules('batch','Batch','trim|required|max_length[10]');
		$this->form_validation->set_rules('day','Day','trim|required|max_length[255]');
		$this->form_validation->set_rules('adate','Adate','trim|required');
		$this->form_validation->set_rules('attendence','Attendence','trim|required|max_length[10]');

		if($this->form_validation->run())     
        {   
            $params = array(
				//
				'course_id' => $this->input->post('course_id'),
				'studentid' => $this->input->post('studentid'),
				'trainerid' => $this->input->post('trainerid'),
				'batch' => $this->input->post('batch'),
				'day' => $this->input->post('day'),
				'adate' => $this->input->post('adate'),
				'attendence' => $this->input->post('attendence'),
            );
			
            $params=$this->security->xss_clean($params);
		
            $attendance_id = $this->Attendance_model->add_attendance($params);
            redirect('attendance/index');
        }
        else
        {  
            $data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
            $data['_view'] = 'attendance/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a attendance
     */
    function edit($id)
    {   
        // check if the attendance exists before trying to edit it
        $data['attendance'] = $this->Attendance_model->get_attendance($id);
        
        if(isset($data['attendance']['id']))
        {
            $this->load->library('form_validation');

			// 
			$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
$this->form_validation->set_rules('trainerid','Trainerid','trim|required|max_length[10]');
$this->form_validation->set_rules('batch','Batch','trim|required|max_length[10]');
$this->form_validation->set_rules('day','Day','trim|required|max_length[255]');
$this->form_validation->set_rules('adate','Adate','trim|required');
$this->form_validation->set_rules('attendence','Attendence','trim|required|max_length[10]');

		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					'course_id' => $this->input->post('course_id'),
'studentid' => $this->input->post('studentid'),
'trainerid' => $this->input->post('trainerid'),
'batch' => $this->input->post('batch'),
'day' => $this->input->post('day'),
'adate' => $this->input->post('adate'),
'attendence' => $this->input->post('attendence'),

                );
				$params=$this->security->xss_clean($params);
                $this->Attendance_model->update_attendance($id,$params);            
                redirect('attendance/index');
            }
            else
            {
				$data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
                $data['_view'] = 'attendance/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The attendance you are trying to edit does not exist.');
    } 

    /*
     * Deleting attendance
     */
    function remove($id)
    {
        $attendance = $this->Attendance_model->get_attendance($id);

        // check if the attendance exists before trying to delete it
        if(isset($attendance['id']))
        {
            $this->Attendance_model->delete_attendance($id);
            redirect('attendance/index');
        }
        else
            show_error('The attendance you are trying to delete does not exist.');
    }
    
}