<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class career extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Career_model');
        $this->load->model('Common_model');
        $this->load->model('Courses_model');
    } 

    /*
     * Listing of career
     */
    function index()
    {
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('career/index?');
        $config['total_rows'] = $this->Career_model->get_all_career_count();
        $this->pagination->initialize($config);

        $data['career'] = $this->Career_model->get_all_career($params);
        
        $data['_view'] = 'career/index';
        $this->load->view('layouts/main2',$data);
    }
/*
     * Adding a new chage status 
     */
	 
	 function status($status,$id)
    {
		$params = array('status' => $status);
		$params=$this->security->xss_clean($params);
		$this->Career_model->update_career($id,$params);        
		redirect(site_url().'career');
    }
    /*
     * Adding a new career ffffff
     */
    function add()
    {   
		
        $this->load->library('form_validation');
			
		//
		$this->form_validation->set_rules('full_name','First Name','trim|required|max_length[255]');
		$this->form_validation->set_rules('last_name','Last Name','trim|required|max_length[255]');
		$this->form_validation->set_rules('email','Email','trim|required|max_length[100]');
		$this->form_validation->set_rules('phn','Phone Number','trim|required|numeric|max_length[12]');
		$this->form_validation->set_rules('gender','Gender','trim|required|max_length[10]');
		$this->form_validation->set_rules('dob','Date of birth','trim|required');
		$this->form_validation->set_rules('caddress','Contact Address','trim|required|max_length[255]');
		$this->form_validation->set_rules('paddress','Permanent Address','trim|required|max_length[255]');
		$this->form_validation->set_rules('state','State','trim|required|max_length[10]');
		$this->form_validation->set_rules('country','Country','trim|required|max_length[10]');
		$this->form_validation->set_rules('areaofexpertise','Areaofexpertise','trim|required|max_length[255]');
		$this->form_validation->set_rules('corrections','Please accept terms','trim|required');
		$this->form_validation->set_rules('actions','Please accept our policy','trim|required');
		$this->form_validation->set_rules('city','Please select city','trim|required');
		
		
		if($this->form_validation->run())     
        {   
			/// upload docsA
				$config['upload_path']   = './uploads/resume'; 
				$config['allowed_types'] = 'doc|pdf'; 
				$config['max_size']      = 1000000; 
				$config['max_width']     = 3000; 
				$config['max_height']    = 3000;  
				$this->load->library('upload', $config);
				$this->upload->initialize($config);
				/////////////////////
				if (!$this->upload->do_upload('resume')) {
					$data['error']= array('error' => $this->upload->display_errors()); 
					var_dump($data);
				 }
					
				else { 
						$data = array('upload_data' => $this->upload->data());
						$imgname=$data['upload_data']['file_name'];	
				}
				
			/// upload avatar
				$configa['upload_path']   = './uploads/avatar'; 
				$configa['allowed_types'] = 'jpg|png|jpeg'; 
				$configa['max_size']      = 1000000; 
				$configa['max_width']     = 3000; 
				$configa['max_height']    = 3000;  
				$this->upload->initialize($configa);
				/////////////////////
				if (!$this->upload->do_upload('avatar')) {
					$data['error']= array('error' => $this->upload->display_errors()); 
					
				 }else { 
						$data = array('upload_data' => $this->upload->data());
						$avatar=$data['upload_data']['file_name'];	
				}	
					
				$params = array(
					//
					'first_name' => $this->input->post('full_name'),
					'last_name' => $this->input->post('last_name'),
					'email' => $this->input->post('email'),
					'phn' => $this->input->post('phn'),
					'gender' => $this->input->post('gender'),
					'dob' => $this->input->post('dob'),
					'caddress' => $this->input->post('caddress'),
					'paddress' => $this->input->post('paddress'),
					'state' => $this->input->post('state'),
					'country' => $this->input->post('country'),
					'city' => $this->input->post('city'),

					'areaofexpertise' => $this->input->post('areaofexpertise'),
					'resume' => $imgname,
					'avatar' => $avatar,
					'exp' => $this->input->post('exp'),

					'corrections' => $this->input->post('corrections'),
					'actions' => $this->input->post('actions'),
				);
					$params=$this->security->xss_clean($params);
					$dddd=$this->Career_model->add_career($params);
				if($dddd){
						$this->load->library('email');
						$this->load->library('sendmail');
						$enquery="Careers";
						$message = $this->sendmail->sendFormsData($enquery,$params,$link,$token,$sTl);
						$to_email = 'shailender@infotonicsmedia.com';
						$this->email->from($this->config->item('forgot'), 'New Form From FPGA website! ' . $this->input->post('firstname') .' '. $this->input->post('lastname')); //from sender, title email
						$this->email->to($to_email);
						$this->email->subject('FPGA::New Form From FPGA website');
						$this->email->message($message);
						$this->email->set_mailtype("html");
						$this->email->send();
						$data['error']='Your Information stored successfully, We will get back to you asap...';
						$data['page']='career';
						$data['_view'] = 'FrontWebsite/career';
						$this->load->view('FrontWebsite/layout/main',$data);
				}else{

						$data['error']=$dddd;
						$data['page']='career';
						$data['_view'] = 'FrontWebsite/career';
						$this->load->view('FrontWebsite/layout/main',$data);
				}
		
		}
        else
        {       
			if($_SESSION['role']=='admin'){
				$data['_view'] = 'career/add';
				$this->load->view('layouts/main2',$data);
			}else{
				$data['errorx']=validation_errors();
				$data['page']='career';
				$data['_view'] = 'FrontWebsite/career';
				$this->load->view('FrontWebsite/layout/main',$data);
			}
        }
    }  

    /*
     * Editing a career
     */
    function edit($id)
    { 
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
 
        // check if the career exists before trying to edit it
        $data['career'] = $this->Career_model->get_career($id);
        
        if(isset($data['career']['id']))
        {
            $this->load->library('form_validation');

			//
			$this->form_validation->set_rules('first_name','First Name','trim|required|max_length[255]');
			$this->form_validation->set_rules('last_name','Last Name','trim|required|max_length[255]');
$this->form_validation->set_rules('email','Email','trim|required|max_length[100]');
$this->form_validation->set_rules('phn','Phn','trim|required|max_length[12]');
$this->form_validation->set_rules('gender','Gender','trim|required|max_length[1]');
$this->form_validation->set_rules('dob','Dob','trim|required');
$this->form_validation->set_rules('caddress','Caddress','trim|required|max_length[255]');
$this->form_validation->set_rules('paddress','Paddress','trim|required|max_length[255]');
$this->form_validation->set_rules('college','College','trim|required|max_length[255]');
$this->form_validation->set_rules('degree','Degree','trim|required|max_length[255]');
$this->form_validation->set_rules('designation','Designation','trim|required|max_length[255]');
$this->form_validation->set_rules('areaofexpertise','Areaofexpertise','trim|required|max_length[255]');
$this->form_validation->set_rules('duration','Duration','trim|required|max_length[50]');
$this->form_validation->set_rules('otherinfo','Otherinfo','trim|required');
$this->form_validation->set_rules('careergoals','Careergoals','trim|required');
$this->form_validation->set_rules('exp','Exp','trim|required|max_length[25]');
$this->form_validation->set_rules('course','Course','trim|required|max_length[255]');
$this->form_validation->set_rules('message','Message','trim|required');

		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'email' => $this->input->post('email'),
					'phn' => $this->input->post('phn'),
					'gender' => $this->input->post('gender'),
					'dob' => $this->input->post('dob'),
					'caddress' => $this->input->post('caddress'),
					'paddress' => $this->input->post('paddress'),
					'college' => $this->input->post('college'),
					'degree' => $this->input->post('degree'),
					'designation' => $this->input->post('designation'),
					'areaofexpertise' => $this->input->post('areaofexpertise'),
					'duration' => $this->input->post('duration'),
					'otherinfo' => $this->input->post('otherinfo'),
					'careergoals' => $this->input->post('careergoals'),
					'exp' => $this->input->post('exp'),
					'course' => $this->input->post('course'),
					'message' => $this->input->post('message'),

                );
				$params=$this->security->xss_clean($params);
                $this->Career_model->update_career($id,$params);            
                redirect('career/index');
            }
            else
            {
				$data['courses'] = $this->Courses_model->get_all_Courses();
                $data['_view'] = 'career/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The career you are trying to edit does not exist.');
    } 

    /*
     * Deleting career
     */
    function remove($id)
    {
        $career = $this->Career_model->get_career($id);

        // check if the career exists before trying to delete it
        if(isset($career['id']))
        {
            $this->Career_model->delete_career($id);
            redirect('career/index');
        }
        else
            show_error('The career you are trying to delete does not exist.');
    }
    
}