<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Contacts extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contacts_model');
        $this->load->model('Courses_model');
    } 

    /*
     * Listing of contacts
     */
    function index()
    {
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('contacts/index?');
        $config['total_rows'] = $this->Contacts_model->get_all_contacts_count();
        $this->pagination->initialize($config);

        $data['contacts'] = $this->Contacts_model->get_all_contacts($params);
        
        $data['_view'] = 'contacts/index';
        $this->load->view('layouts/main2',$data);
    }
	
	/*
     * Adding a new chage status 
     */
	 
	 function status($status,$id)
    {
		$params = array('status' => $status);
		$params=$this->security->xss_clean($params);
		$this->Contacts_model->update_contacts($id,$params);        
		redirect(site_url().'contacts');
    }

    /*
     * Adding a new contacts ffffff
     */
    function add()
    {   
	
        $this->load->library('form_validation');

		//
		$this->form_validation->set_rules('name','Name','trim|required|max_length[255]');
		$this->form_validation->set_rules('email','Email','trim|required|max_length[100]');
		$this->form_validation->set_rules('phn','Phn','trim|required|numeric|max_length[12]');
		$this->form_validation->set_rules('Course','Course','required');
		$this->form_validation->set_rules('subject','Subject','trim|required|max_length[255]');
		$this->form_validation->set_rules('message','Message','trim|required');

		
		if($this->form_validation->run())     
        {   
            $params = array(
				//
				'name' => $this->input->post('name'),
				'email' => $this->input->post('email'),
				'phn' => $this->input->post('phn'),
				'subject' => $this->input->post('subject'),
				'message' => $this->input->post('message'),

            );
            $params=$this->security->xss_clean($params);
			//var_dump($params);exit();
            $bk=$this->Contacts_model->add_contacts($params);
				if($bk){
				$bk=explode(',',$bk);
				
				//generate token
					$token=$bk[1];
					$paramsz = array(
						//
						'validcode' => $bk[1],
					);
					if($this->Contacts_model->update_contacts($bk[0],$paramsz)){
                    $qstring = $this->base64url_encode($token);
                    $url = site_url() . 'main/validate/token/' . $qstring;
                    $link = '<a href="' . $url . '">' . $url . '</a>';
    
                    $this->load->library('email');
                    $this->load->library('sendmail');
                    
                    $message = $this->sendmail->sendValidGuest($this->input->post('fullname'),$this->input->post('email'),$link,$token,$sTl);
                    $to_email = $this->input->post('email');
                    $this->email->from($this->config->item('forgot'), 'FPGA :: Email Validation ' . $this->input->post('firstname') .' '. $this->input->post('lastname')); //from sender, title email
                    $this->email->to($to_email);
                    $this->email->subject('FPGA::Email Validation');
                    $this->email->message($message);
                    $this->email->set_mailtype("html");
    
                    if($this->email->send()){
                        echo '<form action="https://fpga.infotonicsmedia.com/svalidate/c" role="form" id="formid" onsubmit="submitForm(this)" enctype="multipart/form-data" method="post" accept-charset="utf-8">
										
						<div class="col-lg-12 col-md-12">
							<div class="form-group">
							<label class="form-group-label"><span class="text-danger">*</span>Validation Code</label>
							<input required="" class="form-control" placeholder="Validation Code" type="text" name="vcode" value="">
							<span class="text-danger"></span>
						</div> </div>
						<button class="default-btn" type="submit">Submit</button>

						</form>';
						$this->load->library('email');
						$this->load->library('sendmail');
						$enquery="Enquiry / Contact Us";
						$message = $this->sendmail->sendFormsData($enquery,$params,$link,$token,$sTl);
						$to_email = 'shailender@infotonicsmedia.com';
						$this->email->from($this->config->item('forgot'), 'New Form From FPGA website! ' . $this->input->post('firstname') .' '. $this->input->post('lastname')); //from sender, title email
						$this->email->to($to_email);
						$this->email->subject('FPGA::New Form From FPGA website');
						$this->email->message($message);
						$this->email->set_mailtype("html");
						if($this->email->send()){
						
							$data['error']='Your Information stored successfully, We will get back to you asap :).';
						}else{
							$this->session->set_flashdata('flash_message', 'There was a problem sending an email.');
							echo 'error in sending email';
							exit;
						}
                    }else{
						var_dump($this->email->send());
					   $this->session->set_flashdata('flash_message', 'There was a problem sending an email.');
                        exit;
                    }
					}else{echo '2';}
			}

        }
        else
        {       
			if($_SESSION['role']=='admin'){
				$data['_view'] = 'contacts/add';
				$this->load->view('layouts/main2',$data);
			}else{
				 validation_errors();
                $data['courses'] = $this->Courses_model->get_all_courses();
                $data['_view'] = 'FrontWebsite/contactus';
                $this->load->view('FrontWebsite/layout/main',$data
            );
			}
        }
    }  

    

    /*
     * Editing a contacts
     */
    function edit($id)
    {   
			$data = $this->session->userdata;
	if($data['role']!='admin'){
					redirect(site_url().'signup');
				}
        // check if the contacts exists before trying to edit it
        $data['contacts'] = $this->Contacts_model->get_contacts($id);
        
        if(isset($data['contacts']['id']))
        {
            $this->load->library('form_validation');

			//
			$this->form_validation->set_rules('name','Name','trim|required|max_length[255]');
            $this->form_validation->set_rules('email','Email','trim|required|max_length[100]');
            $this->form_validation->set_rules('phn','Phn','trim|required|max_length[12]');
            $this->form_validation->set_rules('subject','Subject','trim|required|max_length[255]');
            $this->form_validation->set_rules('message','Message','trim|required');

		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					'name' => $this->input->post('name'),
					'email' => $this->input->post('email'),
					'phn' => $this->input->post('phn'),
					'subject' => $this->input->post('subject'),
					'message' => $this->input->post('message'),

                );
				$params=$this->security->xss_clean($params);
                $this->Contacts_model->update_contacts($id,$params);            
                redirect('contacts/index');
            }
            else
            {
                $data['_view'] = 'contacts/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The contacts you are trying to edit does not exist.');
    } 

    /*
     * Deleting contacts
     */
    function remove($id)
    {
        $contacts = $this->Contacts_model->get_contacts($id);

        // check if the contacts exists before trying to delete it
        if(isset($contacts['id']))
        {
            $this->Contacts_model->delete_contacts($id);
            redirect('contacts/index');
        }
        else
            show_error('The contacts you are trying to delete does not exist.');
    }
    public function sendRegister($vtoken){
        $message = '';
        $message .= 'Hi,<br>';
        $message .= '<br>';
        $message .= 'Welcome! you have signed up with our website with the following information:<br>';
        $message .= '<br>';
        $message .= '<strong>VALIDATION TOKEN : '.$vtoken.'</strong><br>';
        $message .= '<br>';
        $message .= 'Before you can login, you need to activate and set your Password';
        $message .= '<br>';
        $message .= 'Sincerely yours,<br>';
        $message .= 'Your Own Team :)';
        return $message;
    }
	public function base64url_encode($data) {
      return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
    }

    public function base64url_decode($data) {
      return base64_decode(str_pad(strtr($data, '-_', '+/'), strlen($data) % 4, '=', STR_PAD_RIGHT));
    }
	  function cvalidate()
    {
		$vcode=$_POST['vcode'];
        $token = base64_decode($vcode);
        $cleanToken = $this->security->xss_clean($token);

        $user_info = $this->Contacts_model->isTokenValid($cleanToken); //either false or array();

        if(!$user_info){
            $this->session->set_flashdata('flash_message', 'Token is invalid or expired');
            echo '<div style="width: 100%;" class="alert alert-warning alert-dismissible" role="alert">Token is not validated</div>';
        }else{
			echo '<div style="width: 100%;" class="alert alert-success alert-dismissible" role="alert">Thanks for validating, please check given below details submitted by you.</div>';
		}
	}
}