<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Course_lectures extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_lectures_model');
		$this->load->model('Courses_model');
        $this->load->model('Users_model');
        $this->load->model('Curriculam_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of course_lectures
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('course_lectures/index?');
        $config['total_rows'] = $this->Course_lectures_model->get_all_course_lectures_count();
        $this->pagination->initialize($config);

        $data['course_lectures'] = $this->Course_lectures_model->get_all_course_lectures($params);
        
        $data['_view'] = 'course_lectures/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new course_lectures ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

		//
		$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
$this->form_validation->set_rules('batch_id','Batch_id','trim|required|max_length[10]');
$this->form_validation->set_rules('datetimeof','Datetimeof','trim|required|max_length[10]');
$this->form_validation->set_rules('tid','Tid','trim|required|max_length[10]');
$this->form_validation->set_rules('attendance','Attendance','trim|required|max_length[1]');

		
		if($this->form_validation->run())     
        {   
            $params = array(
				//
				'course_id' => $this->input->post('course_id'),
'studentid' => $this->input->post('studentid'),
'batch_id' => $this->input->post('batch_id'),
'datetimeof' => $this->input->post('datetimeof'),
'tid' => $this->input->post('tid'),
'attendance' => $this->input->post('attendance'),

            );
            $params=$this->security->xss_clean($params);
            $course_lectures_id = $this->Course_lectures_model->add_course_lectures($params);
            redirect('course_lectures/index');
        }
        else
        {       
			
			$data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
				
            $data['_view'] = 'course_lectures/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a course_lectures
     */
    function edit($id)
    {   
        // check if the course_lectures exists before trying to edit it
        $data['course_lectures'] = $this->Course_lectures_model->get_course_lectures($id);
        
        if(isset($data['course_lectures']['id']))
        {
            $this->load->library('form_validation');

			//
			$this->form_validation->set_rules('course_id','Course_id','trim|required|max_length[10]');
$this->form_validation->set_rules('studentid','Studentid','trim|required|max_length[10]');
$this->form_validation->set_rules('batch_id','Batch_id','trim|required|max_length[10]');
$this->form_validation->set_rules('datetimeof','Datetimeof','trim|required|max_length[10]');
$this->form_validation->set_rules('tid','Tid','trim|required|max_length[10]');
$this->form_validation->set_rules('attendance','Attendance','trim|required|max_length[1]');

		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					'course_id' => $this->input->post('course_id'),
'studentid' => $this->input->post('studentid'),
'batch_id' => $this->input->post('batch_id'),
'datetimeof' => $this->input->post('datetimeof'),
'tid' => $this->input->post('tid'),
'attendance' => $this->input->post('attendance'),

                );
				$data['courses'] = $this->Courses_model->get_all_Courses();
            $data['users'] = $this->Users_model->user_info();
            $data['curriculam'] = $this->Curriculam_model->get_all_curriculam_list();
				$params=$this->security->xss_clean($params);
                $this->Course_lectures_model->update_course_lectures($id,$params);            
                redirect('course_lectures/index');
            }
            else
            {
                $data['_view'] = 'course_lectures/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The course_lectures you are trying to edit does not exist.');
    } 

    /*
     * Deleting course_lectures
     */
    function remove($id)
    {
        $course_lectures = $this->Course_lectures_model->get_course_lectures($id);

        // check if the course_lectures exists before trying to delete it
        if(isset($course_lectures['id']))
        {
            $this->Course_lectures_model->delete_course_lectures($id);
            redirect('course_lectures/index');
        }
        else
            show_error('The course_lectures you are trying to delete does not exist.');
    }
    
}