<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Payments extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Payments_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of payments
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('payments/index?');
        $config['total_rows'] = $this->Payments_model->get_all_payments_count();
        $this->pagination->initialize($config);

        $data['payments'] = $this->Payments_model->get_all_payments($params);
        
        $data['_view'] = 'payments/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new payments ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

		//
		
		
		if($this->form_validation->run())     
        {   
            $params = array(
				//
				
            );
            $params=$this->security->xss_clean($params);
            $payments_id = $this->Payments_model->add_payments($params);
            redirect('payments/index');
        }
        else
        {       
			
			
				
            $data['_view'] = 'payments/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a payments
     */
    function edit($id)
    {   
        // check if the payments exists before trying to edit it
        $data['payments'] = $this->Payments_model->get_payments($id);
        
        if(isset($data['payments']['id']))
        {
            $this->load->library('form_validation');

			//
			
		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					
                );
				$params=$this->security->xss_clean($params);
                $this->Payments_model->update_payments($id,$params);            
                redirect('payments/index');
            }
            else
            {
                $data['_view'] = 'payments/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The payments you are trying to edit does not exist.');
    } 

    /*
     * Deleting payments
     */
    function remove($id)
    {
        $payments = $this->Payments_model->get_payments($id);

        // check if the payments exists before trying to delete it
        if(isset($payments['id']))
        {
            $this->Payments_model->delete_payments($id);
            redirect('payments/index');
        }
        else
            show_error('The payments you are trying to delete does not exist.');
    }
    
}