<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Transactions extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Transactions_model');
        $this->load->model('Courses_model');
        $this->load->model('Users_model');
        $this->load->model('Course_schedule_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){   
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of transactions
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('transactions/index?');
        $config['total_rows'] = $this->Transactions_model->get_all_transactions_count();
        $this->pagination->initialize($config);

        $data['transactions'] = $this->Transactions_model->get_all_transactions($params);
        
        $data['_view'] = 'transactions/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new transactions ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

				//
		$this->form_validation->set_rules('transactions','transactions','trim|required|max_length[100]');

		// imgs icons 
		if($this->form_validation->run())     
        {   
			/// upload docsA
				/// upload docsA
				$config['upload_path']   = './uploads/transactions'; 
				$config['allowed_types'] = 'gif|jpg|png'; 
				$config['max_size']      = 1000000; 
				$config['max_width']     = 3000; 
				$config['max_height']    = 3000;  
				$this->load->library('upload', $config);
				$this->upload->initialize($config);
				/////////////////////
				if ( ! $this->upload->do_upload('imgs')) {
					$data['error']= array('error' => $this->upload->display_errors()); 
					//var_dump($data);echo '1'; exit();
					$data['_view'] = 'transactions/add';
					$this->load->view('layouts/main2',$data);
				 }
					
				 else { 
					$data = array('upload_data' => $this->upload->data());
					$imgname=$data['upload_data']['file_name'];	
					/////////////////////
				$params = array(
					//
					
					'transactions' => $this->input->post('transactions'),
					'imgs' => $imgname,
					'icons' => '<i class="flaticon-design"></i>',

				);
				$params=$this->security->xss_clean($params);
				$transactions_id = $this->Transactions_model->add_transactions($params);
				redirect('transactions/index');
			}
			
			
		}
        else
        {       
			
			
				
            $data['_view'] = 'transactions/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a transactions
     */
    function edit($id)
    {   
        // check if the transactions exists before trying to edit it
        $data['transactions'] = $this->Transactions_model->get_transactions($id);
        
        if(isset($data['transactions']['id']))
        {
            $this->load->library('form_validation');

			//
			$this->form_validation->set_rules('transactions','transactions','trim|required|max_length[100]');
					
			if($this->form_validation->run())     
            {   
				/// upload docsA
					$config['upload_path']   = './uploads/transactions'; 
					$config['allowed_types'] = 'gif|jpg|png'; 
					$config['max_size']      = 1000000; 
					$config['max_width']     = 3000; 
					$config['max_height']    = 3000;  
					$this->load->library('upload', $config);
				$this->upload->initialize($config);
					/////////////////////
					if ( ! $this->upload->do_upload('imgs')) {
						$data['error']= array('error' => $this->upload->display_errors()); 
						//var_dump($data);echo '1'; exit();
					 }
						
					 else { 
						$data = array('upload_data' => $this->upload->data());
						$imgname=$data['upload_data']['file_name'];	
						
						/////////////////////
					$params = array(
						//
						
						'transactions' => $this->input->post('transactions'),
						'imgs' => $imgname,
						'icons' => '<i class="flaticon-design"></i>',

					);
					$params=$this->security->xss_clean($params);
					$this->Transactions_model->update_transactions($id,$params);            
					redirect('transactions/index');
				 }
				 $data['_view'] = 'transactions/edit';
				$this->load->view('layouts/main2',$data);
            }
            else
            {
                $data['_view'] = 'transactions/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The transactions you are trying to edit does not exist.');
    } 

    /*
     * Deleting transactions
     */
    function remove($id)
    {
        $transactions = $this->Transactions_model->get_transactions($id);

        // check if the transactions exists before trying to delete it
        if(isset($transactions['id']))
        {
            $this->Transactions_model->delete_transactions($id);
            redirect('transactions/index');
        }
        else
            show_error('The transactions you are trying to delete does not exist.');
    }
    
}