<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Userinfo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Userinfo_model');
		$data = $this->session->userdata;
	if($data['role']!='admin'){
	        redirect(site_url().'signup');
	    }
    } 

    /*
     * Listing of userinfo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('userinfo/index?');
        $config['total_rows'] = $this->Userinfo_model->get_all_userinfo_count();
        $this->pagination->initialize($config);

        $data['userinfo'] = $this->Userinfo_model->get_all_userinfo($params);
        
        $data['_view'] = 'userinfo/index';
        $this->load->view('layouts/main2',$data);
    }

    /*
     * Adding a new userinfo ffffff
     */
    function add()
    {   
        $this->load->library('form_validation');

		//
		
		
		if($this->form_validation->run())     
        {   
            $params = array(
				//
				
            );
            $params=$this->security->xss_clean($params);
            $userinfo_id = $this->Userinfo_model->add_userinfo($params);
            redirect('userinfo/index');
        }
        else
        {       
			
			
				
            $data['_view'] = 'userinfo/add';
            $this->load->view('layouts/main2',$data);
        }
    }  

    /*
     * Editing a userinfo
     */
    function edit($id)
    {   
        // check if the userinfo exists before trying to edit it
        $data['userinfo'] = $this->Userinfo_model->get_userinfo($id);
        
        if(isset($data['userinfo']['id']))
        {
            $this->load->library('form_validation');

			//
			
		
			if($this->form_validation->run())     
            {   
                $params = array(
					//
					
                );
				$params=$this->security->xss_clean($params);
                $this->Userinfo_model->update_userinfo($id,$params);            
                redirect('userinfo/index');
            }
            else
            {
                $data['_view'] = 'userinfo/edit';
                $this->load->view('layouts/main2',$data);
            }
        }
        else
            show_error('The userinfo you are trying to edit does not exist.');
    } 

    /*
     * Deleting userinfo
     */
    function remove($id)
    {
        $userinfo = $this->Userinfo_model->get_userinfo($id);

        // check if the userinfo exists before trying to delete it
        if(isset($userinfo['id']))
        {
            $this->Userinfo_model->delete_userinfo($id);
            redirect('userinfo/index');
        }
        else
            show_error('The userinfo you are trying to delete does not exist.');
    }
    
}