<!-- Terms Conditions Area -->
        <div class="terms-conditions-area pt-100 pb-70">
           <div class="container">
               <div class="section-title text-center">
                   <span>Privacy Policy</span>
                   <h2><?=$pageinfo['title'];?></h2>
               </div>
               <div class="row pt-45">
                   <div class="col-lg-12">
                       <div class="single-content">
                           <?=$pageinfo['description'];?>
                           <ol>
                             <li>Introduction</li>
                           </ol>
                           <p>Welcome to Webicle Solutions.</p>
                           <p>Webicle Solutions (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates gatewaytofpga.com (hereinafter referred to as &ldquo;Service&rdquo;).</p>
                           <p>Our Privacy Policy governs your visit to gatewaytofpga.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
                           <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise de ned in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
                           <p>Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&ldquo;agreement&rdquo;).</p>
                           <ol start="2">
                             <li>De nitions</li>
                           </ol>
                           <p>SERVICE means the gatewaytofpga.com website operated by Webicle Solutions.</p>
                           <p>PERSONAL DATA means data about a living individual who can be identi ed from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                           <p>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                           <p>COOKIES are small les stored on your device (computer or mobile device).</p>
                           <p>DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
                           <p>DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more e ectively.</p>
                           <p>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
                           <p>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
                           <ol start="3">
                             <li>Information Collection and Use</li>
                           </ol>
                           <p>We collect several di erent types of information for various purposes to provide and improve our Service to you.</p>
                           <ol start="4">
                             <li>Types of Data Collected</li>
                           </ol>
                           <p>Personal Data</p>
                           <p>While using our Service, we may ask you to provide us with certain personally identi able information that can be used to contact or identify you (&ldquo;Personal Data&rdquo;).</p>
                           <p>Personally identi able information may include, but is not limited to:</p>
                           <ul>
                             <li>Email address</li>
                             <li>First name and last name</li>
                             <li>Phone number</li>
                             <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                             <li>Cookies and Usage Data</li>
                           </ul>
                           <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
                           <p>Usage Data</p>
                           <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (&ldquo;Usage Data&rdquo;).</p>
                           <p>This Usage Data may include information such as your computer&rsquo;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identi ers and other diagnostic data.</p>
                           <p>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identi ers and other diagnostic data.</p>
                           <p>Tracking Cookies Data</p>
                           <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                           <p>Cookies are les with a small amount of data which may include an anonymous unique identi er. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
                           <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                           <p>Examples of Cookies we use:</p>
                           <p>0.1. Session Cookies: We use Session Cookies to operate our Service.</p>
                           <p>0.2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</p>
                           <p>0.3. Security Cookies: We use Security Cookies for security purposes.</p>
                           <p>0.4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                           <p>Other Data</p>
                           <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on <a href="https://policymaker.io/non-disclosure-agreement/">education, quali cation, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on mar</a>ital status, family members, social security (or other taxpayer identi cation) number, o&nbsp;&nbsp;&nbsp; ce location and other data. </p>
                           <ol start="5">
                             <li>Use of Data</li>
                           </ol>
                           <p>Webicle Solutions uses the collected data for various purposes:</p>
                           <ul>
                             <li>to provide and maintain our Service;</li>
                             <li>to notify you about changes to our Service;</li>
                             <li>to allow you to participate in interactive features of our Service when you chooseto do so;</li>
                             <li>to provide customer support;</li>
                             <li>to gather analysis or valuable information so that we can improve our Service;</li>
                             <li>to monitor the usage of our Service;</li>
                             <li>to detect, prevent and address technical issues;</li>
                             <li>to ful l any other purpose for which you provide it;</li>
                             <li>to carry out our obligations and enforce our rights arising from any contractsentered into between you and us, including for billing and collection;</li>
                             <li>to provide you with notices about your account and/or subscription, includingexpiration and renewal notices, email-instructions, etc.;</li>
                             <li>to provide you with news, special o ers and general information about othergoods, services and events which we o er that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                             <li>in any other way we may describe when you provide the information;</li>
                             <li>for any other purpose with your consent.</li>
                           </ul>
                           <ol start="6">
                             <li>Retention of Data</li>
                           </ol>
                           <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                           <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
                           <ol start="7">
                             <li>Transfer of Data</li>
                           </ol>
                           <p>Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may di er from those of your jurisdiction.</p>
                           <p>If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.</p>
                           <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                           <p>Webicle Solutions will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
                           <ol start="8">
                             <li>Disclosure of Data</li>
                           </ol>
                           <p>We may disclose personal information that we collect, or you provide:</p>
                           <ul>
                             <li>Disclosure for Law Enforcement.</li>
                           </ul>
                           <p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
                           <ul>
                             <li>Business Transaction.</li>
                           </ul>
                           <p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>
                           <ul>
                             <li>Other cases. We may disclose your information also: <ul>
                                 <li>to our subsidiaries and a liates;</li>
                                 <li>to contractors, service providers, and other third parties we use to support ourbusiness;</li>
                                 <li>to ful ll the purpose for which you provide it;</li>
                                 <li>for the purpose of including your company&rsquo;s logo on our website;</li>
                                 <li>for any other purpose disclosed by us when you provide the information;</li>
                                 <li>with your consent in any other cases;</li>
                                 <li>if we believe disclosure is necessary or appropriate to protect the rights,property, or safety of the Company, our customers, or others.</li>
                               </ul>
                             </li>
                           </ul>
                           <ol start="9">
                             <li>Security of Data</li>
                           </ol>
                           <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                           <ol start="10">
                             <li>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</li>
                           </ol>
                           <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
                           <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                           <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at info@gatewaytofpga.com.</p>
                           <p>In certain circumstances, you have the following data protection rights:</p>
                           <ul>
                             <li>the right to access, update or to delete the information we have on you;</li>
                             <li>the right of recti cation. You have the right to have your information recti ed ifthat information is inaccurate or incomplete;</li>
                             <li>the right to object. You have the right to object to our processing of your PersonalData;</li>
                             <li>the right of restriction. You have the right to request that we restrict theprocessing of your personal information;</li>
                             <li>the right to data portability. You have the right to be provided with a copy of yourPersonal Data in a structured, machine-readable and commonly used format;</li>
                             <li>the right to withdraw consent. You also have the right to withdraw your consentat any time where we rely on your consent to process your personal information;</li>
                           </ul>
                           <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.</p>
                           <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
                           <ol start="11">
                             <li>Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</li>
                           </ol>
                           <p>CalOPPA is the rst state law in the nation to require commercial websites and online services to post a privacy policy. The law&rsquo;s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identi able information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.</p>
                           <p>According to CalOPPA we agree to the following:</p>
                           <ul>
                             <li>users can visit our site anonymously;</li>
                             <li>our Privacy Policy link includes the word &ldquo;Privacy&rdquo;, and can easily be found on thehome page of our website;</li>
                             <li>users will be noti ed of any privacy policy changes on our Privacy Policy Page;</li>
                             <li>users are able to change their personal information by emailing us atinfo@gatewaytofpga.com.</li>
                           </ul>
                           <p>Our Policy on &ldquo;Do Not Track&rdquo; Signals:</p>
                           <p>We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
                           <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
                           <ol start="12">
                             <li>Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</li>
                           </ol>
                           <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:</p>
                           <p>0.1. What personal information we have about you. If you make this request, we will return to you:</p>
                           <ul>
                             <li>The categories of personal information we have collected about you.</li>
                             <li>The categories of sources from which we collect your personal information.</li>
                             <li>The business or commercial purpose for collecting or selling your personalinformation.</li>
                             <li>The categories of third parties with whom we share personal information.</li>
                             <li>The speci c pieces of personal information we have collected about you.</li>
                             <li>A list of categories of personal information that we have sold, along with thecategory of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.</li>
                             <li>A list of categories of personal information that we have disclosed for abusiness purpose, along with the category of any other company we shared it with.</li>
                           </ul>
                           <p>Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.</p>
                           <ul>
                             <li>To delete your personal information. If you make this request, we willdelete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identi cation of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</li>
                             <li>To stop selling your personal information. We don&rsquo;t sell or rent yourpersonal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a &ldquo;sale&rdquo; under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.</li>
                           </ul>
                           <p>If you submit a request to stop selling your personal information, we will stop making such transfers.</p>
                           <p>Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.</p>
                           <p>To exercise your California data protection rights described above, please send your request(s) by email: info@gatewaytofpga.com.</p>
                           <p>Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To nd out more, visit the o&nbsp; cial California Legislative Information website. The CCPA took e ect on 01/01/2020.</p>
                           <ol start="13">
                             <li>Service Providers</li>
                           </ol>
                           <p>We may employ third party companies and individuals to facilitate our Service (&ldquo;Service Providers&rdquo;), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
                           <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
                           <ol start="14">
                             <li>Analytics</li>
                           </ol>
                           <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
                           <ol start="15">
                             <li>CI/CD tools</li>
                           </ol>
                           <p>We may use third-party Service Providers to automate the development process of our Service.</p>
                           <ol start="16">
                             <li>Behavioral Remarketing</li>
                           </ol>
                           <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>
                           <ol start="17">
                             <li>Payments</li>
                           </ol>
                           <p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
                           <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint e ort of brands like Visa, Mastercard, American Express and Discover.</p>
                           <p>PCI-DSS requirements help ensure the secure handling of payment information.</p>
                           <ol start="18">
                             <li>Links to Other Sites</li>
                           </ol>
                           <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&rsquo;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                           <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                           <p>For example, the outlined <a href="#">privacy policy</a> has been made using <a href="#">PolicyMaker.io</a>, a free <a href="https://policymaker.io/privacy-policy/">tool that helps create high-quality legal documents. PolicyMaker&rsquo;s privacy policy generator is an easy-to-use tool for creating a</a>
                             <a href="#"> privacy policy for blog,</a>
                             <a href="#"> website, e</a>commerce store or mobile app.
                           </p>
                           <ol start="19">
                             <li>Children&rsquo;s Privacy</li>
                           </ol>
                           <p>Our Services are not intended for use by children under the age of 18 (&ldquo;Child&rdquo; or &ldquo;Children&rdquo;).</p>
                           <p>We do not knowingly collect personally identi able information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without veri cation of parental consent, we take steps to remove that information from our servers.</p>
                           <ol start="20">
                             <li>Changes to This Privacy Policy</li>
                           </ol>
                           <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                           <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming e ective and update &ldquo;e ective date&rdquo; at the top of this Privacy Policy.</p>
                           <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are e ective when they are posted on this page.</p>
                           <ol start="21">
                             <li>Contact Us</li>
                           </ol>
                           <p>If you have any questions about this Privacy Policy, please contact us by email: info@gatewaytofpga.com.</p>
                       </div>
                   </div>
               </div>
           </div>
       </div>
       <!-- Terms Conditions Area End -->
