<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Assignments_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assignments by id
     */
    function get_assignments($id)
    {
        return $this->db->get_where('assignments',array('id'=>$id))->row_array();
    }
	
	
    function get_assignments_bid($id)
    {
		$this->db->where('batch_id',$id);
		$this->db->order_by('id', 'desc');
        return $this->db->get('assignments')->row_array();
    }
   
    
    /*
     * Get all assignments count
     */
    function get_all_assignments_count()
    {
        $this->db->from('assignments');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assignments
     */
    function get_all_assignments($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
		$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assignments')->result_array();
    }
        
    /*
     * function to add new assignments
     */
    function add_assignments($params)
    {
        $this->db->insert('assignments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assignments
     */
    function update_assignments($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assignments',$params);
    }
    
    /*
     * function to delete assignments
     */
    function delete_assignments($id)
    {
        return $this->db->delete('assignments',array('id'=>$id));
    }
}
