<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Assign_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get assign by id
     */
    function get_assign($id)
    {
        return $this->db->get_where('assign',array('id'=>$id))->row_array();
    }
	
	function get_aassing($id)
    {
        return $this->db->get_where('assign',array('batch'=>$id,'studentid'=>$_SESSION['id']))->row_array();
    }
	
    /*
     * Get marks by id
     */
    function get_marksid($id)
    {
        return $this->db->get_where('assign',array('sbcid'=>$id))->row_array();
    }
    /*
     * Get all assign count
     */
    function get_all_assign_count()
    {
        $this->db->from('assign');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all assign
     */
    function get_all_assign($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('assign')->result_array();
    }
        
    /*
     * function to add new assign
     */
    function add_assign($params)
    {
		date_default_timezone_set("Asia/Kolkata");
        $this->db->insert('assign',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update assign
     */
    function update_assign($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('assign',$params);
    }
    
    /*
     * function to delete assign
     */
    function delete_assign($id)
    {
        return $this->db->delete('assign',array('id'=>$id));
    }
}
