<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Batch_student_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get batch_student by id
     */
    function get_batch_student($id)
    {
        return $this->db->get_where('batch_student',array('id'=>$id))->row_array();
    }
    function get_batch_student_cid($id)
    {
        return $this->db->get_where('batch_student',array('course_id'=>$id))->row_array();
    }
    function get_batch_student_uid($id)
    {
        return $this->db->get_where('batch_student',
			array('course_id'=>$id,'tid'=>$_SESSION['id']))->row_array();
    }
    
    /*
     * Get all batch_student count
     */
    function get_all_batch_student_count()
    {
        $this->db->from('batch_student');
        return $this->db->count_all_results();
    }
   function get_courses_schedule_count()
    {
        $this->db->from('batch_student');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all batch_student
     */
    function get_all_batch_student($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('batch_student')->result_array();
    }
     /*
     * Get all batch_student by id
     */
    function get_all_batch_student_tid($bid)
    {
        $this->db->where('tid',$_SESSION['id']);
        $this->db->where('batch_id',$bid);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
		return $this->db->get('batch_student')->result_array();
        // echo $this->db->last_query();
    }
    function get_all_batch_student_sid($bid)
    {
        $this->db->where('sid',$_SESSION['id']);
        $this->db->where('batch_id',$bid);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
		return $this->db->get('batch_student')->result_array();
        // echo $this->db->last_query();
    }
    function get_all_student_info($bid)
    {
        $this->db->where('batch_id',$bid);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
		return $this->db->get('batch_student')->result_array();
        // echo $this->db->last_query();
    }
        
    /*
     * function to add new batch_student
     */
    function add_batch_student($params)
    {
        $this->db->insert('batch_student',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update batch_student
     */
    function update_batch_student($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('batch_student',$params);
    }
    
    /*
     * function to delete batch_student
     */
    function delete_batch_student($id)
    {
        return $this->db->delete('batch_student',array('id'=>$id));
    }
}
