<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Bookacall_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bookacall by id
     */
    function get_bookacall($id)
    {
        return $this->db->get_where('bookacall',array('id'=>$id))->row_array();
    }
    /*
     * function to update contacts
     */
	 function check_validate($id)
    {
        return $this->db->get_where('bookacall',array('validcode'=>$id))->row_array();
    }
	
    function update_vcontacts($id,$params)
    {
        $this->db->where('validcode',$id);
        return $this->db->update('bookacall',$params);
    }
    
    /*
     * Get all bookacall count
     */
    function get_all_bookacall_count()
    {
        $this->db->from('bookacall');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bookacall
     */
    function get_all_bookacall($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('bookacall')->result_array();
    }
        
    /*
     * function to add new bookacall
     */
    function add_bookacall($params)
    {
        $this->db->insert('bookacall',$params);
        $rtyyr=$this->db->insert_id();
		if($rtyyr){ 
			$lastid= $this->db->insert_id();
			$valid_code=mt_rand(0,10000);
			$this->db->where('id',$lastid);
			$yue=$this->db->update('bookacall',array('validcode'=>$valid_code));
			if (!$yue){
				return false;
				exit();
			}else{
				return $lastid.','.$valid_code;
				exit();
			}
		}
		elseif($this->db->error()){
			return $this->db->error()['message'];
		}else{
			return false;
		}
    }
    
    /*
     * function to update bookacall
     */
    function update_bookacall($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('bookacall',$params);
    }
    
    /*
     * function to delete bookacall
     */
    function delete_bookacall($id)
    {
        return $this->db->delete('bookacall',array('id'=>$id));
    }
	public function base64url_encode($data) {
      return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
    }

    public function base64url_decode($data) {
      return base64_decode(str_pad(strtr($data, '-_', '+/'), strlen($data) % 4, '=', STR_PAD_RIGHT));
    }
}
