<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Buycourse_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get buycourse by id
     */
    function get_buycourse($id)
    {
        return $this->db->get_where('buycourse',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all buycourse count
     */
    function get_all_buycourse_count()
    {
        $this->db->from('buycourse');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all buycourse
     */
    function get_all_buycourse($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('buycourse')->result_array();
    }
        
    /*
     * function to add new buycourse
     */
    function add_buycourse($params)
    {
        $this->db->insert('buycourse',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update buycourse
     */
    function update_buycourse($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('buycourse',$params);
    }
    
    /*
     * function to delete buycourse
     */
    function delete_buycourse($id)
    {
        return $this->db->delete('buycourse',array('id'=>$id));
    }
}
