<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Common_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get common by id
     */
    function get_country($id = null, $cid =  null)
    {
		if($id!=null){
			$gets=array('id'=>$id);
		}else{
			$gets=array('1'=>'1');
		}
        return $this->db->get_where('countries',$gets)->result_array();
    }
    
   function get_state($id = null, $cid =  null)
    {
		if($cid=='1'){
			$this->db->where('id',$id);
			$state= $this->db->get('states')->row_array();
		}else{
			if($id!=null){
				$this->db->where('country_id',$id);
			}else{
				$this->db->where('1','1');
			}
			
			$statez= $this->db->get('states')->result_array();
			$state='';
			foreach($statez as $cs){
					$state.='<option value="'.$cs["id"].'">'.$cs["name"].'</option>';
			}
		}
		return $state;
    }
	
    function get_city($id = null, $cid =  null)
    {
		if($cid=='1'){
			$this->db->where('id',$id);
			$city= $this->db->get('cities')->row_array();
		}else{
			if($id!=null){
				$gets=array('state_id'=>$id);
			}else{
				$gets=array('1'=>'1');
			}
			$cityz= $this->db->get_where('cities',$gets)->result_array();
			$city='';
			foreach($cityz as $cs){
					$city.='<option value="'.$cs["id"].'">'.$cs["name"].'</option>';
			}
		}
		return $city;
    }
   function get_batch($id = null, $cid =  null)
    {
		if($id!=null){
			$gets=array('course_id'=>$id);
		}else{
			$gets=array('1'=>'1');
		}
        $cityz= $this->db->get_where('course_schedule',$gets)->result_array();
		$city='';
		foreach($cityz as $cs){
				$city.='<option value="'.$cs["id"].'">'.$cs["batch_name"].'</option>';
		}
		return $city;
    }
   
   
   
}
