<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Contacts_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contacts by id
     */
    function get_contacts($id)
    {
        return $this->db->get_where('contacts',array('id'=>$id))->row_array();
    }
    //token
    function isTokenValid($id)
    {
        return $this->db->get_where('bookacall',array('validcode'=>$id))->row_array();
    }
	function check_validate($id)
    {
        return $this->db->get_where('contacts',array('validcode'=>$id))->row_array();
    }
	
    /*
     * Get all contacts count
     */
    function get_all_contacts_count()
    {
        $this->db->from('contacts');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all contacts
     */
    function get_all_contacts($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('contacts')->result_array();
    }
        
    /*
     * function to add new contacts
     */
    function add_contacts($params)
    {
        $this->db->insert('contacts',$params);
        $rtyyr=$this->db->insert_id();
		if($rtyyr){ 
			$lastid= $this->db->insert_id();
			$valid_code=mt_rand(0,10000);
			$this->db->where('id',$lastid);
			$yue=$this->db->update('contacts',array('validcode'=>$valid_code));
			if (!$yue){
				return false;
				exit();
			}else{
				return $lastid.','.$valid_code;
				exit();
			}
		}
		elseif($this->db->error()){
			return $this->db->error()['message'];
		}else{
			return false;
		}
    }
    
    /*
     * function to update contacts
     */
    function update_contacts($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('contacts',$params);
    }
    
	/*
     * function to update contacts
     */
    function update_vcontacts($id,$params)
    {
        $this->db->where('validcode',$id);
        return $this->db->update('contacts',$params);
    }
    
	
    /*
     * function to delete contacts
     */
    function delete_contacts($id)
    {
        return $this->db->delete('contacts',array('id'=>$id));
    }
}
