<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
  
class Courses_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get courses by id
     */
    function get_courses($id)
    {
        return $this->db->get_where('courses',array('id'=>$id))->row_array();
    }
	function get_courses_id($id)
    {
        return $this->db->get_where('courses',array('id'=>$id))->row_array();
    }
	
	function get_courses_id_all($id)
    {
        return $this->db->get_where('allcourseinfo',array('id'=>$id))->row_array();
    }
	
////////////////////
    function get_courses_all($title)
    {
        return $this->db->get_where('allcourseinfo',array('title'=>$title))->row_array();
    }
	////////////////////
    function get_courses_all_byid($title)
    {
        return $this->db->get_where('allcourseinfo',array('course_id'=>$title))->result_array();
    }
////////////////////
    function get_courses_info_bytid($title,$cid)
    {
        return $this->db->get_where('allcourseinfo',array('tutorid'=>$title,'id'=>$cid))->row_array();
    }

    ////////////////////
    function get_courses_all_bytid($uid,$params = array())
    {
        $this->db->where('tutorid',$uid);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
		$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('allcourseinfo')->result_array();
    }
     ////////////////////
    function get_courses_all_info($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
			$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('allcourseinfo')->result_array();
    }
    
    /*
     * Get all courses count
     */
    function get_all_courses_count()
    {
        $this->db->from('courses');
        return $this->db->count_all_results();
    }
    function get_categ_courses_count($ctitle)
    {
        $ctr=$this->db->get_where('category',array('category'=>$ctitle))->row_array();
        // echo $this->db->last_query();
        // var_dump($ctr);
		$this->db->where('categ',$ctr['id']);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
		$this->db->order_by('id', 'desc');
		$this->db->from('courses');
        return $this->db->count_all_results();
    }
    function get_courses_all_bytid_count($ctitle)
    {

        $this->db->where('tutorid',$uid);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
		$this->db->from('courses');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all courses
     */
    function get_all_courses($params = array())
    {
        if($_SESSION['role']!='admin'){
			$this->db->where('status','Y');
		}
		$this->db->order_by('id', 'desc');
        // if(isset($params) && !empty($params))
        // {
            // $this->db->limit($params['limit'], $params['offset']);
        // }
        return $this->db->get('courses')->result_array();
    }
	/*
     * Get all courses
     */
    function get_all_courses_like($params = array())
    {
        $this->db->like('title',$params['search']);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('courses')->result_array();
    }
	
	/*
     * Get all courses
     */
    function get_allcours_list()
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        
        return $this->db->get('courses')->result_array();
    }
	
	
    function get_all_categ_courses($ctitle,$params)
    {
		$ctr=$this->db->get_where('category',array('category'=>$ctitle))->row_array();
        $this->db->where('categ',$ctr['id']);
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('courses')->result_array();
    }
        
    /*
     * function to add new courses
     */
    function add_courses($params)
    {
        $this->db->insert('courses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update courses
     */
    function update_courses($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('courses',$params);
    }
    
    /*
     * function to delete courses
     */
    function delete_courses($id)
    {
        return $this->db->delete('courses',array('id'=>$id));
    }
}
