<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Course_details_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course_details by id
     */
    function get_course_details($id)
    {
        return $this->db->get_where('course_details',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all course_details count
     */
    function get_all_course_details_count()
    {
        $this->db->from('course_details');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all course_details
     */
    function get_all_course_details($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('course_details')->result_array();
    }
        
    /*
     * function to add new course_details
     */
    function add_course_details($params)
    {
        $this->db->insert('course_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course_details
     */
    function update_course_details($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('course_details',$params);
    }
    
    /*
     * function to delete course_details
     */
    function delete_course_details($id)
    {
        return $this->db->delete('course_details',array('id'=>$id));
    }
}
