<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Curriculam_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get curriculam by id
     */
    function get_curriculam($id)
    {
        return $this->db->get_where('curriculam',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all curriculam count
     */
    function get_all_curriculam_count()
    {
        $this->db->from('curriculam');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all curriculam by course id
     */
    function get_curriculam_cid($cid)
    {
        $this->db->where('course_id',$cid);
        $this->db->order_by('posotion', 'asc');
        return $this->db->get('curriculam')->result_array();
    }
     /*
     * Get all curriculam
     */
    function get_all_curriculam($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('curriculam')->result_array();
    }
     /*
     * Get all curriculam
     */
    function get_all_curriculam_list()
    {
        if($_SESSION['role']!='admin'){
			$this->db->where('status','Y');}
		$this->db->order_by('id', 'desc');
        return $this->db->get('curriculam')->result_array();
    }
        
    /*
     * function to add new curriculam
     */
    function add_curriculam($params)
    {
        $this->db->insert('curriculam',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update curriculam
     */
    function update_curriculam($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('curriculam',$params);
    }
    
    /*
     * function to delete curriculam
     */
    function delete_curriculam($id)
    {
        return $this->db->delete('curriculam',array('id'=>$id));
    }
}
