<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Internship_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get internship by id
     */
    function get_internship($id)
    {
        return $this->db->get_where('internship',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all internship count
     */
    function get_all_internship_count()
    {
        $this->db->from('internship');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all internship
     */
    function get_all_internship($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('internship')->result_array();
    }
        
    /*
     * function to add new internship
     */
    function add_internship($params)
    {
        $this->db->insert('internship',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update internship
     */
    function update_internship($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('internship',$params);
    }
    
    /*
     * function to delete internship
     */
    function delete_internship($id)
    {
        return $this->db->delete('internship',array('id'=>$id));
    }
}
