<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Payments_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get payments by id
     */
    function get_payments($id)
    {
        return $this->db->get_where('payments',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all payments count
     */
    function get_all_payments_count()
    {
        $this->db->from('payments');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all payments
     */
    function get_all_payments($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('payments')->result_array();
    }
        
    /*
     * function to add new payments
     */
    function add_payments($params)
    {
        $this->db->insert('payments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update payments
     */
    function update_payments($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('payments',$params);
    }
    
    /*
     * function to delete payments
     */
    function delete_payments($id)
    {
        return $this->db->delete('payments',array('id'=>$id));
    }
}
