<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Trainers_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trainers by id
     */
    function get_trainers($id)
    {
        return $this->db->get_where('trainers',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all trainers count
     */
    function get_all_trainers_count()
    {
        $this->db->from('trainers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all trainers
     */
    function get_all_trainers($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('trainers')->result_array();
    }
    /*
     * Get all trainers rand
     */
    function get_rand_list($vals)
    {
        $this->db->order_by('id', 'RANDOM');
        $this->db->limit($vals,'0');
        return $this->db->get('trainers')->result_array();
    }    
    /*
     * function to add new trainers
     */
    function add_trainers($params)
    {
        $this->db->insert('trainers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trainers
     */
    function update_trainers($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('trainers',$params);
    }
    
    /*
     * function to delete trainers
     */
    function delete_trainers($id)
    {
        return $this->db->delete('trainers',array('id'=>$id));
    }
}
