<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Userinfo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get userinfo by id
     */
    function get_userinfo($id)
    {
        return $this->db->get_where('userinfo',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all userinfo count
     */
    function get_all_userinfo_count()
    {
        $this->db->from('userinfo');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all userinfo
     */
    function get_all_userinfo($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('userinfo')->result_array();
    }
        
    /*
     * function to add new userinfo
     */
    function add_userinfo($params)
    {
        $this->db->insert('userinfo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update userinfo
     */
    function update_userinfo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('userinfo',$params);
    }
    
    /*
     * function to delete userinfo
     */
    function delete_userinfo($id)
    {
        return $this->db->delete('userinfo',array('id'=>$id));
    }
}
