<?php
/* 
 * Generated by MegaBuilder v1.0 
 * www.MegaBuilder.com
 */
 
class Videos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get videos by id
     */
    function get_videos($id)
    {
        return $this->db->get_where('videos',array('id'=>$id))->row_array();
    }
    function get_videoss()
    {
        return $this->db->get_where('videos',array('1'=>'1'))->result_array();
    }
    
    /*
     * Get all videos count
     */
    function get_all_videos_count()
    {
        $this->db->from('videos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all videos
     */
    function get_all_videos($params = array())
    {
        if($_SESSION['role']!='admin'){$this->db->where('status','Y');}
	$this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('videos')->result_array();
    }
        
    /*
     * function to add new videos
     */
    function add_videos($params)
    {
        $this->db->insert('videos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update videos
     */
    function update_videos($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('videos',$params);
    }
    
    /*
     * function to delete videos
     */
    function delete_videos($id)
    {
        return $this->db->delete('videos',array('id'=>$id));
    }
}
